"""
Extract MNIST test samples (one per digit 0-9), run PyTorch inference,
and emit test_inputs.h + pytorch_outputs.txt for C comparison.

Run from project root or this directory:
    python examples/mnist_test_model/extract_samples.py
"""

from __future__ import annotations

import os
import sys

import torch
from torchvision import datasets, transforms

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_EXAMPLES_ROOT = os.path.join(_THIS_DIR, "..")
_PROJECT_ROOT = os.path.join(_THIS_DIR, "..", "..")

sys.path.insert(0, _EXAMPLES_ROOT)
from mnist_cnn import MNISTConvNet

NUM_SAMPLES = 10
WEIGHTS_PATH = os.path.join(_EXAMPLES_ROOT, "mnist_cnn_weights.pth")
OUT_DIR = _THIS_DIR
TEST_INPUTS_H = os.path.join(OUT_DIR, "test_inputs.h")
PYTORCH_OUT = os.path.join(OUT_DIR, "pytorch_outputs.txt")


def main():
    if not os.path.isfile(WEIGHTS_PATH):
        print(f"ERROR: weights not found: {WEIGHTS_PATH}")
        print("Run: python examples/mnist_cnn.py")
        sys.exit(1)

    device = torch.device("cpu")
    transform = transforms.Compose(
        [
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,)),
        ]
    )

    data_dir = os.path.join(_PROJECT_ROOT, "data")
    test_set = datasets.MNIST(data_dir, train=False, download=True, transform=transform)

    # One index per label 0..9
    indices_by_label: dict[int, int] = {}
    for idx in range(len(test_set)):
        _, label = test_set[idx]
        if label not in indices_by_label:
            indices_by_label[label] = idx
        if len(indices_by_label) == NUM_SAMPLES:
            break

    if len(indices_by_label) < NUM_SAMPLES:
        raise RuntimeError("Could not find one sample per digit class")

    ordered = sorted(indices_by_label.items(), key=lambda x: x[0])  # by label 0..9

    model = MNISTConvNet().to(device)
    state = torch.load(WEIGHTS_PATH, map_location=device, weights_only=True)
    model.load_state_dict(state)
    model.eval()

    h_lines = [
        "/* Auto-generated by extract_samples.py — do not edit */",
        "#ifndef TEST_INPUTS_H_",
        "#define TEST_INPUTS_H_",
        "",
        f"#define NUM_SAMPLES {NUM_SAMPLES}",
        "",
    ]

    pytorch_lines: list[str] = []

    for i, (label, dataset_idx) in enumerate(ordered):
        img, _ = test_set[dataset_idx]
        # img: (1, 28, 28) NCHW
        x = img.unsqueeze(0).to(device)
        with torch.no_grad():
            logits = model(x).squeeze(0).cpu().numpy()

        # Flatten NCHW (1,28,28) -> 784 in row-major (same as NHWC for C=1)
        flat = img.reshape(-1).numpy().tolist()

        h_lines.append(f"/* sample {i}: true label {label}, dataset index {dataset_idx} */")
        h_lines.append(f"static const float sample_{i}[784] = {{")
        # 8 floats per line
        for row_start in range(0, 784, 8):
            chunk = flat[row_start : row_start + 8]
            h_lines.append("    " + ", ".join(f"{v:.8f}f" for v in chunk) + ",")
        h_lines.append("};")
        h_lines.append("")

        logits_str = " ".join(f"{float(v):.9e}" for v in logits)
        pytorch_lines.append(
            f"{logits_str}  # sample={i} label={label} idx={dataset_idx}"
        )

    h_lines.append("static const float* test_samples[NUM_SAMPLES] = {")
    h_lines.append("    " + ", ".join(f"sample_{i}" for i in range(NUM_SAMPLES)))
    h_lines.append("};")
    h_lines.append("")
    h_lines.append("#endif /* TEST_INPUTS_H_ */")

    with open(TEST_INPUTS_H, "w", encoding="utf-8") as f:
        f.write("\n".join(h_lines) + "\n")

    with open(PYTORCH_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(pytorch_lines) + "\n")

    print(f"Wrote {TEST_INPUTS_H}")
    print(f"Wrote {PYTORCH_OUT}")


if __name__ == "__main__":
    main()
